spring:
  application:
    name: libera-ticket
  servlet:
    multipart:
      max-file-size: 100MB
  jackson:
    time-zone: Asia/Seoul
  messages:
    basename: messages
    encoding: UTF-8
  task:
    scheduling:
      enabled: true

  #  datasource:
#    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
#    username: sa
#    password:
  datasource:
    url: jdbc:postgresql://maglev.proxy.rlwy.net:58833/railway?sslmode=require
    username: postgres
    password: NweWNWhpsYKRAQrxXviLnwRpUYtdefiB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

  h2:
    console:
      enabled: true
  thymeleaf:
    cache: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 8080

app:
  base-url: ${APP_BASE_URL:http://localhost:8080}
  result-notice-date: 2025-10-25
  cancel-token-expire-days: 30
  event:
    poster: "/img/Libera_poster_resized.jpg"     # 포스터(히어로 배경)
    program_image: "/img/Libera_program_resized.jpg"  # 프로그램 안내 단일 이미지
    wonnam: "img/wonnam.jpg"


solapi:
  api-key: ${SOLAPI_API_KEY}
  api-secret: ${SOLAPI_API_SECRET}
  from: ${SOLAPI_FROM}

resend:
  api-key: ${RESEND_API_KEY}
  from: ${RESEND_FROM}

logging:
  level:
    org:
      springframework:
        scheduling: DEBUG